### ISSUE TITLE
Use `MultiCurrency` in PredictionMarkets to abstract the base asset

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/zeitgeist#100]
Right now it is assumed the base asset for all prediction markets is the ZTG. 

In the future we will want to use a stablecoin such as aUSD (Acala's stablecoin) instead. In order to do this we must abstract the logic for payouts to use `MultiCurrency` trait instead of a mix between `Balances` and `Shares` (aka Tokens).

**Comment by Chralt98** [comment]
I know, that we use the ORML (open-runtime-module-library) of PureStake (aka Moonbeam) and currently this library has only the [`MultiReservableCurrency`](https://github.com/PureStake/open-runtime-module-library/blob/master/tokens/src/lib.rs#L1157-L1278) but not the needed [`MultiNamedReservableCurrency`](https://github.com/open-web3-stack/open-runtime-module-library/commit/23f70926ec5ac78b9aad215fe78837554eee723e) for the prediction markets pallet to later use aUSD as base asset. 

The required `MultiNamedReservableCurrency` was recently added by [Open-Web-Stack](https://github.com/open-web3-stack). It is now the question, if it is allowed to use such a new commit or to wait for more stability in the new feature.

`MultiNamedReservableCurrency` is required because the prediction markets pallet uses a reserve identifier for the `CurrencyOf` calls [here for example](https://github.com/zeitgeistpm/zeitgeist/blob/main/zrml/prediction-markets/src/lib.rs#L270).

As a result, we could have only one `MultiCurrency` in the prediction markets pallet to manage all the currencies and tokens at one place, which is the point of this issue.

**Comment by Chralt98** [comment]
Additionally I would rename `Shares` to `ZCurrencies` then, because it is a central point to manage all currencies (base asset and other assets) and not just the outcome assets / token shares.
