### ISSUE TITLE
Align existential deposits of foreign assets with ZTG

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/zeitgeist#1002]
Currently the existential deposit for ZTG is 0.005 = $0.0032
The existential deposit for DOT is 1 = $5.42

To me it doesn't makes sense that we would allocate storage for $0.01 worth of one asset but not $5 worth of another. We should align the existential deposits so that the values are roughly equal

**Comment by TvrtkoM** [comment]
Existential deposit on polkadot relay chain is 1 dot, so if we make existential deposit lower than that when someone transfers less than 1 dot back it's going to be lost anyway.
maybe instead of lowering existential deposit we should make extrinsics that would put user balance below 1 dot fail or just disable submitting them
