### ISSUE TITLE
Timestamp based market state transition can stall the chain

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/zeitgeist#1141]
Prediction markets can either transition states based on block or timestamp deadlines. In the case of timestamps, a mechanism is used that caches (a derivative of) the last timestamp within `LastTimeFrame` that was used for checking which markets have to transition their state. The state transition function is invoked at the beginning of every block (`on_initialize`) and it contains a loop that queries `now() - <LastTimeFrame<T>>::get()) / block_time` times the storage, in order words the number of blocks that could have been created between now and the last time the function was invoked. 

```rust
let current_time_frame = Self::calculate_time_frame_of_moment(<zrml_market_commons::Pallet<T>>::now()).saturating_add(1);

...

for time_frame in last_time_frame.saturating_add(1)..=current_time_frame ...

...

pub(crate) fn calculate_time_frame_of_moment(time: MomentOf<T>) -> TimeFrame {
      time.saturated_into::<TimeFrame>().saturating_div(MILLISECS_PER_BLOCK.into())
}
```

Should a chain stall for whatever reason, this function could become so heavy that either only the parachain or neither the parachain nor the relaychain will be able to process the block within the given time constraints.

This is the loop:
https://github.com/zeitgeistpm/zeitgeist/blob/3d9bbff91219bb324f047427224ee318061a6d43/zrml/prediction-markets/src/lib.rs#L3028-L3038

An alternative solution must be implemented to avoid this situation. The solution could:
- Rely on users to transit the state of the market
- Use bins that cache multiple "timeframes" (i.e. vectors of 300 elements that group markets that transit within a delta of 1 hour, assuming 12s block time)

**Comment by sea212** [comment]
Raising priority to critical as just 13 hours ago Rococo was upgraded and stalled all chains. Once enough time passes, the chain has to be forked again.
It cannot be risked that this potentially could also happen on Polkadot, where we would have to rely on 28 days of referendum time until the mainnet would be fully functional again.

**Comment by Chralt98** [comment]
> Use bins that cache multiple "timeframes" (i.e. vectors of 300 elements that group markets that transit within a delta of 1 hour, assuming 12s block time)

Even this approach means we would need to iterate over multiple markets in a for loop. Ok, this solution reduces the number of timeframes to iterate, but not the number of markets to iterate. It looks like it's just a less bad solution.

> Rely on users to transit the state of the market

Yeah, to let users manually resolve markets is definitely an approach that works in a sustained way! Zeitgeist could batch all resolution requests together, whenever the chain produces blocks again.

I am currently thinking about another approach.. Ok, there is another option:

Remove timestamp markets completely: If a user wants to enter a timestamp, the front end abstracts this away. The future timestamp is translated to the estimated future block number internally. If the chain stalls or the blockchain does not produce blocks in time (but delays), we have the problem that the actual market resolution happens after the specified timestamp. But this would happen at the moment too, if the chain stalls... With the asynchronous backing update of polkadot, the parachain will be able to produce blocks in 6 seconds, but not 12 seconds anymore. So, it should be kept in mind, that the market resolution could also happen before the specified timestamp, because suddenly blocks can be produced much faster. With our current solution, this behaviour wouldn't be mitigated either (without a storage migration), because at market creation time the end timestamp was calculated on the assumption to produce blocks in 12 seconds. So in this case, we would need a storage migration to transform and increase all timeframes in `MarketIdsPerTimeFrame`.

We could migrate all timestamp-based markets to block-based markets with a migration.

**Comment by Chralt98** [comment]
On the other hand when thinking this through, let us imagine the following example:

The market end specified as timestamp by the user is 1 year from now. This translates internally to `1 * 365 * 24 * 60 * 60 = 31,536,000 seconds` which are 2,628,000 blocks (assuming 12 seconds blocktime). In the current implementation `create_market` does the following:

```rust
MarketPeriod::Timestamp(range) => MarketIdsPerCloseTimeFrame::<T>::try_mutate(
    Self::calculate_time_frame_of_moment(range.end),
    |ids| -> Result<u32, DispatchError> {
        ids.try_push(*market_id).map_err(|_| <Error<T>>::StorageOverflow)?;
        Ok(ids.len() as u32)
    },
),
``` 

The `calculate_time_frame_of_moment` translates the specified `range.end` from milliseconds to a block number representation (dividing `range.end` / milliseconds_per_block). The crux is that this is only to group multiple timestamp based markets together in the same time frame. It also allows to be independent from actual block number resolution, because the actual timestamp `now` can be queried at every block to check if timestamp markets can resolve.

Suppose the chain stalls now. We can't resolve markets during a chain stall and all ending timestamp based markets are scheduled for the point at which the block production continues. For block-based markets the ending is postponed by the duration of the chain stall, which is also not ideal if there is a hard boundary at which the market should resolve. But what markets should resolve at a time limit? Do we actually have such time critical markets? So are timestamp markets really required?

I propose if we really need the timestamp market feature, we should either expose an extrinsic to resolve the timestamp market or we store timestamp markets in a list sorted by time, which is processed in `on_idle`. In this case, we are not sure either if the time critical market actually resolves at a specific time, but it would resolve nearly at the time. The problem with that solution is clear: Blocks could be full and timestamp markets wouldn't resolve in time.. But I do think this is an edge case.

**Comment by Chralt98** [comment]
<img width="899" alt="battery_station_fork_implications" src="https://github.com/zeitgeistpm/zeitgeist/assets/33418719/4d260580-31cf-475e-96c7-e79860794d87">

Market 730 is still in predictionMarkets -> marketIdsPerCloseTimeFrame scheduled at time frame (block number) `141,317,700`. Currently now is at time frame `141,483,129` (now = `1697797548104`, time frame = now / 12000). Means the market should indeed be already resolved. I expect this is due to the battery station stall leading to the situation that during the stall the market should have been resolved, but since we forked the battery station to a previous block, but the timestamp doesn't care about this, the market is still not resolved and from now on will never be.

This is a prime example of our current issue here.

Same thing happened to market id 670, 731, 567, 690. This is absolutely mandatory to fix now!

**Comment by sea212** [comment]
I am in favor of applying an automatic solution, as for some state transitions it is mandatory to happen in time. Besides that, it is not very user friendly approach to make an inherently automatic process (state *machine*) manual, albeit being a practical solution in case it is mandatory and no other way is found.

We will not remove timestamps, as it is a intuitive way to describe when events happened in the past or will happen in the future within the natural world. Using block numbers and some conversion mechanism is not applicable, as there is an unknown time drift in every blockchain, i.e. blocks are not always produced exactly every N seconds, ideally within a margin of 1%, when something goes wrong it can also be dramatically more.

Either way, manual or automatic, we cannot reduce the markets that we have to iterate over in total, as every market's state has to be transited at some point. The only freedom that we have is to apply scheduling to non time critical state transitions. Every state transition within the prediction markets pallet has some margin afaik, but the prediction market pallets also controls the opening and closing of a pool, and those have to happen at the exact time.
The main issue in the current solution is that in any case, for every expected time delta between two blocks, four storage reads are guaranteed, no matter if there are markets to transit the state for or not. I'd like to emphasize that the problem is not that there are too many markets to transit the state for.

Based on all of that, my conclusion is that we need an algorithm that:
1. Creates bins over multiple time deltas, for example all markets that transit between N and N + 1 hour are in one bin
2. Bins are sorted, such that we can abort reading the next market's information from storage as soon as we reach the first market that did not reach it's state transition deadline yet
3. Market transition is priority based
     a. Opening and closing markets and pools has real time priority: The algorithm will try to close and open all markets and their associated pools as the first thing in `on_initialize`, such that it can utilize as much weight as possible for that.
     b. All other state transitions go into `on_idle`, if the weight is insufficient the remaining state transitions will be moved into the next block.

**Comment by Chralt98** [comment]
> 1. Creates bins over multiple time deltas, for example all markets that transit between N and N + 1 hour are in one bin

Do you agree that we already have a kind of bin, but for [`MILLISECONDS_PER_BLOCK`](https://github.com/zeitgeistpm/zeitgeist/blob/6c466cde06ddcf5c0a2b2357afa36264c4f75cae/zrml/prediction-markets/src/lib.rs#L2264) ?

So this essentially means for extend this function `calculate_time_frame_of_moment` to return a bin of span 1 hour instead of one block. Means exactly: `time.saturated_into::<TimeFrame>().saturating_div(300u64.saturating_mul(MILLISECS_PER_BLOCK.into()))` (60 minutes * 60 seconds = 3600 seconds divided by 12 seconds per block is market close and openings are stored for every 300 blocks).

> 2. Bins are sorted, such that we can abort reading the next market's information from storage as soon as we reach the first market that did not reach it's state transition deadline yet

Ok, this sounds reasonable.

> a. Opening and closing markets and pools has real time priority: The algorithm will try to close and open all markets and their associated pools as the first thing in on_initialize, such that it can utilize as much weight as possible for that.

What if our chain stalls for a prolonged period of time in which the number of markets need to be closed is such a high amount that we can't put all state transitions into one block. Then we need to put the rest into the next block, right? So, it's also the requirement.

> b. All other state transitions go into on_idle, if the weight is insufficient the remaining state transitions will be moved into the next block.

In specific terms, which state transitions are not mandatory right now in [`on_initialize`](https://github.com/zeitgeistpm/zeitgeist/blob/6c466cde06ddcf5c0a2b2357afa36264c4f75cae/zrml/prediction-markets/src/lib.rs#L1715-L1822) ?

**Comment by Chralt98** [comment]
I found another possible solution to tackle our problem, which drastically reduces developer time and provides a fast hot fix. Here is the idea:

Leave the automatic opening and closing as it currently is in on_initialize :-) . Just remove [the for-loop](https://github.com/zeitgeistpm/zeitgeist/blob/6c466cde06ddcf5c0a2b2357afa36264c4f75cae/zrml/prediction-markets/src/lib.rs#L2888), which caused the chain stalls in the past. Remove the [`LastTimeFrame`](https://github.com/zeitgeistpm/zeitgeist/blob/6c466cde06ddcf5c0a2b2357afa36264c4f75cae/zrml/prediction-markets/src/lib.rs#L1808) storage item. Consider a "broken" market to be a market, which has a opening or closing time that is already in the past, but the state does not reflect that ("broken" market detection). Provide an extrinsic that checks if a market is "broken" and if it is, closes or opens it. This extrinsic can be fee-less, because spam is basically prevented. So, whenever there is a chain stall, this case happens rarely, we can manually solve this problem on-chain, if it ever occurs. We can avoid the large processing of a sorted bin, because outside users can inject their knowledge from outside of the chain and it can be verified on-chain (market can be checked if it is broken on-chain). Otherwise we'll always have the problem that there are too many markets to open and close in one block or we need to calculate beforehand how many markets can be processed in one block and put the residue into the next block.

**Comment by sea212** [comment]
This solution is sufficient for now. We should incorporate the last couple of minutes of unprocessed markets and ignore anything beyond that. Logs & Events should indicate that some markets could not be processed.
