### ISSUE TITLE
[Runtime] TransactionPayment misconfiguration set fees for weights to zero

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/zeitgeist#425]
**Summary**
The default value for the transaction fee adjustment multiplier is set to 0 every block.

**Analysis**
In the runtime we configure the transaction payment pallet to use the [default implementation for the `FeeMultiplierUpdate`](https://github.com/zeitgeistpm/zeitgeist/blob/b6d3a3342d1687ae825e78f68c31625ae2a15723/runtime/src/lib.rs#L528). The default implementation of the `MultiplierUpdate` trait [uses the default values of the generics](https://github.com/paritytech/substrate/blob/acb44df78015906174daf359b40916b7bef58c57/frame/transaction-payment/src/lib.rs#L132-L152) for the getter functions. [The fee multiplier is updated after every block](https://github.com/paritytech/substrate/blob/acb44df78015906174daf359b40916b7bef58c57/frame/transaction-payment/src/lib.rs#L313-L319). During the update it uses the maximum value between the newly calculated fee multiplier and the `min()` function of the `MultiplierUpdate` trait. Unfortunately the default value of the numeric type is the additive neutral element 0, leading to the fee [multiplier being updated to `max(0,0) = 0`](https://github.com/paritytech/substrate/blob/acb44df78015906174daf359b40916b7bef58c57/frame/transaction-payment/src/lib.rs#L172-L225).

**Solution**
Implement `MultiplierUpdate` properly, ensuring that the functions use the multiplicative neutral element 1.

**Comment by Chralt98** [comment]
I think the `MultiplierUpdate` was just [updated to zero](https://github.com/paritytech/substrate/blob/acb44df78015906174daf359b40916b7bef58c57/frame/transaction-payment/src/lib.rs#L313-L319), because the [default implementation of the `Convert` trait](https://github.com/paritytech/substrate/blob/acb44df78015906174daf359b40916b7bef58c57/primitives/runtime/src/traits.rs#L288-L292) uses the default value of the type `Multiplier`. 

Therefore the [max function of `TargetedFeeAdjustment`](https://github.com/paritytech/substrate/blob/acb44df78015906174daf359b40916b7bef58c57/frame/transaction-payment/src/lib.rs#L172-L225) was never used.
