### ISSUE TITLE
[Pallets] Execute migrations for parachain-staking

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/zeitgeist#462]
Execute all `parachain-staking` migrations (between [`a1956695d7eeb83f095908b56cce3b3e69e039c4`](https://github.com/PureStake/moonbeam/tree/a1956695d7eeb83f095908b56cce3b3e69e039c4) and [`45257659f04b28dd4927b5dc611fac6f9e8905fd`](a1956695d7eeb83f095908b56cce3b3e69e039c4)

Relevant migrations:

- [ ] https://github.com/PureStake/moonbeam/pull/970
- [ ] https://github.com/PureStake/moonbeam/pull/810
- [x] https://github.com/PureStake/moonbeam/pull/1096 - irrelevant, since the list `bottom_candidates` is empty on our live chains (to be more precise, no bottom candidates exist that have to be moved top candidates)

**Comment by 4meta5** [comment]
@sea212 All 3 migrations are not related so they can be executed in the same block if necessary. Uncomment the required migrations and functions if they are used in the migration.

I don't see where the migrations are used in #458 , moonbeam uses pallet-migrations instead of on_runtime_upgrade in the pallet so these migrations are not executed by default if you do not have pallet-migrations in your runtimes.

**Comment by 4meta5** [comment]
That should work. If you have any trouble with it, feel free to ping me on Riot.
