### ISSUE TITLE
[PM] Audit liquidity functions for CPMM markets

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/zeitgeist#481]
The liquidity functions that are used to add and remove liquidity for a pool are in their current state already a part of the runtime since Battery Park testnet. Nevertheless their application was not as thoroughly tested on the test networks as the other operations.
Before mainnet launch, those functions should be audited carefully.

**Comment by sea212** [comment]
Some things I noticed during a fast scan-over, please verify:

- Charges fee twice (swap and exit fee) in specific asset exit
- Single asset exit functions do nothing with the exit fee and all assets exit functions transfer them to the pool. In both cases, they should be burned, otherwise they will be unusable but still increase the total supply.
- Two `ExitFee` definitions that are not coupled: in `consts` module and in pallet `Config`
- `pool_exit` does not regard `ExitFee` when calculating the amount of asset tokens retrieved.

**Comment by maltekliemann** [comment]
Exit fees have been implemented in #518. In particular, we remove the constant `EXIT_FEE`.

Per default, exit fees are substracted from the amount of tokens that the LP receives when withdrawing from the pool. This means the remaining LPs get richer for staying in the pool. In order to prevent exploits, this does not apply when the pool is `Closed` or `Clean`.

The single-asset operations must take trading fees in addition to swaps fees, as they are implemented using pool join/exit operations followed by a series of swaps. To prevent exploits like "trading" using single-asset liquidity operations, these operations are now disabled on `Closed` pools.
