### ISSUE TITLE
[simple_disputes] Disputes resolve to last dispute without global dispute

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#489]
On a market with `simple_disputes` as DRM, I can ping-pong disputes back and forth until `MaxDisputes` is reached. But then, instead of creating a global dispute, the market just resolves to the last reported outcome after `DisputePeriod`. It doesn't seem like global disputes are implemented, right now (or am I missing something?): https://github.com/zeitgeistpm/zeitgeist/blob/9ca3d7e71c42fc1904d7ecfc4aa88003e19a8a5c/zrml/prediction-markets/src/lib.rs#L818-L828

If there are three or more outcomes, this allows someone using two accounts to "game" the outcome of the market to an outcome of their choice.

There are two possible solutions:

- Implement token holder vote when `MaxDisputes` is reached
- Disable `simple_disputes` (not pretty, since then we've only got the authorized DRM, which requires a great deal of trust in the oracle and authorized arbiter)

**Comment by Chralt98** [comment]
Don't forget the [extrinsic description](https://github.com/zeitgeistpm/zeitgeist/pull/559/commits/4ca263044fa2e7cb6031823de3f8f29467e5eca9) in the PR.

**Comment by Chralt98** [comment]
I thought about implementing, that the global dispute mechanism (voting on disputes) is started after `MaxDisputes` is reached, but this leads to unintended consequences. That's why it's reasonable to use another extrinsic OR a time based system to actually start the global dispute mechanism. 

Assume, that after `MaxDisputes` the global dispute mechanism starts (people can vote on disputes). Some malicious and rich actor only needs to spam `MaxDisputes` disputes to be the only one who can get a vote.
