### ISSUE TITLE
[prediction-markets] Should the oracle count as correct reporter?

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#598]
During testing, I had a closer look at `on_resolution`:

https://github.com/zeitgeistpm/zeitgeist/blob/d2f1784e29fb071bf714791159af8c168fc94584/zrml/prediction-markets/src/lib.rs#L1603-L1735

If there are multiple disputes, the bonds of the losing disputors are slashed and distributed in equal parts among the winning disputors. But currently the oracle is not counted towards the correct reporters, even if it did report correctly, and does not receive their share of the slashed funds.

I think that when the oracle reports correctly, either the oracle or the market creator should be counted towards the correct reporters. The idea of using the market creator comes from the fact that the creator is responsible for providing the oracle bond, and thus bears the risk. But I'm with OK either.

**Comment by Chralt98** [comment]
[Here in this tests](https://github.com/zeitgeistpm/zeitgeist/blob/3243f304df4937f43654927f82ea64623b485a8a/zrml/prediction-markets/src/tests.rs#L1348-L1413), it's only a disputor who gets the loosing `DisputeBonds`, but not the market creator or the oracle.

[This test case](https://github.com/zeitgeistpm/zeitgeist/blob/3243f304df4937f43654927f82ea64623b485a8a/zrml/prediction-markets/src/tests.rs#L1240-L1346) shows, that when the reported outcome of the oracle is not the highest among the disputes, then the market creators `OracleBond` gets slashed and the oracle account itself looses nothing. 

Let us look at [these lines](https://github.com/zeitgeistpm/zeitgeist/blob/3243f304df4937f43654927f82ea64623b485a8a/zrml/prediction-markets/src/tests.rs#L1325-L1326). The `OracleBond` of the market creator is transferred to the correct disputors. In the other case (if the oracle was correct), the `OracleBond` gets returned.

 So, there is a higher incentive to `dispute` an outcome, when the reported outcome is actually wrong, because there is the `OracleBond` reward. If the oracle reported the correct outcome, then the market creator gets the `OracleBond` back, which is enough reward (at least in my opinion). 
The `dispute` of a different outcome to the reported outcome of the oracle is disincentivised in the first place, if everybody thinks, that the oracle is right (because the `OracleBond` is returned to the market creator). In short: Everybody knows, that there is no `OracleBond` reward in case of a different `dispute` outcome. Because the disputor, who bets on the reported outcome, has no chance to get the `OracleBond` it's reasonable for him to not share his reward with the oracle or the market reporter.

So I would leave it as it is for now.

**Comment by Chralt98** [comment]
I looked at the bond size of the [`DisputeBond`](https://github.com/zeitgeistpm/zeitgeist/blob/314c2548f5b96738525beae43818632b50c60afe/primitives/src/constants.rs#L67-L68) and the [`OracleBond`](https://github.com/zeitgeistpm/zeitgeist/blob/314c2548f5b96738525beae43818632b50c60afe/primitives/src/constants.rs#L79). They differ very much in size. 

Because the DisputeBond is much bigger, I could imagine to share the dispute rewards between the market creator and the disputor, who has bet on the same outcome as the oracle. 

But it should be rare, that many accounts `dispute` on a wrong (and not reported) outcome. But nevertheless just one `DisputeBond` is much higher than the `OracleBond` with the current parameter constants.

We also have to look at the risks of each actor. Even if the disputor bet on the reported outcome, the disputor took the risk of loosing one `DisputeBond` with an optional `DisputeFactor`. The market creator took only the risk of the `OracleBond`, but it gets returned anyways if the outcome resolves to be the reported. So, I see no reason for the market creator to get it, when the disputor took the most risk.
