### ISSUE TITLE
[primitives] Remove one variant from `MarketPeriod`

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#616]
I'm wondering if we could remove MarketPeriod in favor of just `Range<BlockNumber>` or `Range<Timestamp>`. Right now, we're using this:

```rust
pub enum MarketPeriod<BN, M> {
    Block(Range<BN>),
    Timestamp(Range<M>),
}
```

It seems to me like unnecessary trouble to offer two ways of storing time points, and be forced to put every functionality involving `MarketPeriod` into a `match` expression, especially since the `Timestamp` version is calculable from the `Block` version using a linear transformation (provided correct function of the chain). We never make any use of having these two representations. Instead, every time we use the market period, we have a match expression where both arms contain essentially the same functionality, except that the `Timestamp` arm requires extra calculation. I guess there's an argument for rather using `Range<Timestamp>`, because it's more resilient against skipped blocks or a stalled chain.

**Comment by sea212** [comment]
I am closing this issue because this is no option. Feel free to reopen for discussion.

We cannot derive the timestamp from the blocknumber or vice versa because the block production time on chain is unreliable. On the other hand, we cannot remove the block number and solely use timestamps because chains will eventually (hopefully) use the Futarchy governance mechanism, and the chains internally use the block number as a measurement of passed time and causal order of things. Externally, people will use timestamps because they are used to that kind of representation and the world as a whole is based on that, internally the chains should still be able to apply governance based on their internal measurement of time, block numbers.
