### ISSUE TITLE
[PM] Consider setting an upper bound for the lifetime of a market

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/zeitgeist#624]
See https://github.com/zeitgeistpm/zeitgeist/pull/614#issuecomment-1126763123

**Comment by maltekliemann** [comment]
I wouldn't mind having a maximum period of one year. This actually gives us some more flexibility when writing code.

For example, let's say we want to remove the CPMM. But we have to keep the old code around for as long as there still exist markets with CPMM pools. Unless we figure out an acceptable way to migrating CPMM to Rikiddo, we now have to keep around the old code because someone created a market that runs for 10 years.
