### ISSUE TITLE
Investigate why clippy doesn't report unchecked integer arithmetic

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#625]
For example, we have the following code snippet: https://github.com/zeitgeistpm/zeitgeist/blob/693c5c0039948787322b3f35e83dc8a298bb482b/zrml/prediction-markets/src/lib.rs#L975-L988

Why does clippy not warn about this?

**Comment by Chralt98** [comment]
First I thought, that [this would get inherited](https://github.com/zeitgeistpm/zeitgeist/blob/ae4551db41bf919f63036220a99e8bd4d2fe7a3d/primitives/src/constants.rs#L1-L5). But this assumption turns out to be false. It has to do with the type.

```rust
// Regard this types:
pub type Balance = u128;
pub const OracleBond: Balance = 50 * CENT;
pub const ValidityBond: Balance = 50 * CENT;
pub const ReportingPeriod: u32 = BLOCKS_PER_DAY as _;

...

// error: integer arithmetic detected
let _test_integer_arithmetic_1 = 42u32 + 42u32;
// error: integer arithmetic detected
let _test_integer_arithmetic_2 = 42u32 + T::ReportingPeriod::get();
// error: integer arithmetic detected
let _test_integer_arithmetic_3 =
    T::ReportingPeriod::get() + T::ReportingPeriod::get();
// no clippy error
let non_integer_type_conversion: MomentOf<T> = T::ReportingPeriod::get().into();
let _test_integer_arithmetic_4 = non_integer_type_conversion + 42u32.into();
// no clippy error
let required_bond = T::ValidityBond::get() + T::OracleBond::get();
```

Although `Balance` is `u128`, clippy doesn't get, that `ValidityBond` and `OracleBond` are actually `u128` too. 
So whenever the assignment to a variable is not directly an integer, then `-Dclippy::integer_arithmetic` wouldn't detect it.

**Comment by Chralt98** [comment]
I realised, that MomentOf<T> is not so easy to identify as an integer.

```rust
type Moment: AtLeast32Bit + Copy + Default + Parameter + MaxEncodedLen;
```

Or look at `Balance`:

```rust
type Balance: Balance + MaybeSerializeDeserialize + Debug + MaxEncodedLen;
```
https://github.com/zeitgeistpm/zeitgeist/blob/ae4551db41bf919f63036220a99e8bd4d2fe7a3d/zrml/prediction-markets/src/lib.rs#L117-L125
So just from the perspective of the prediction markets pallet, it's not easy for clippy to identify them as integers.

**Comment by Chralt98** [comment]
https://github.com/rust-lang/rust-clippy/issues/8968#issuecomment-1151328241

Sounds promising.
