### ISSUE TITLE
[prediction_markets] Remove `MarketStatus` field from market status transition events like `MarketResolved`

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#655]

**Comment by saboonikhil** [comment]
Are they going to be available somewhere else? I believe `market_status` was added in events where they're changing since it would be in subsquid perspective to have every change come from chain. @sea212

**Comment by vivekvpandya** [comment]
> Are they going to be available somewhere else? I believe `market_status` was added in events where they're changing since it would be in subsquid perspective to have every change come from chain. @sea212

I think event name provide status information hence we should be able to remove status from the event.

**Comment by saboonikhil** [comment]
> > Are they going to be available somewhere else? I believe `market_status` was added in events where they're changing since it would be in subsquid perspective to have every change come from chain. @sea212
> 
> I think event name provide status information hence we should be able to remove status from the event.

If we're certain that the logic will remain unchanged in the future and removing them would save us some storage, I'm ok with it.

**Comment by saboonikhil** [comment]
In fact, changes to market aren't as complex as to pool here -> #466.

**Comment by sea212** [comment]
I don't see any benefit to this. Storage is not a problem because the events are cleaned up one block after they are emitted and computational time (for encoding) also doesn't matter for those couple of bytes, especially because those events are emitted rarely. As Nikhil mentioned, we have consciously decided to add them in the past to explicitly mark state changes in any event, such that any software can easily keep track of those.
