### ISSUE TITLE
Should a non-oracle reported stake ZTG?

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#698]
If the oracle fails to report and another user steps up to the plate, should they stake ZTG?

I think so. Although we don't want to discourage people from reporting the market, we definitely want to discourage people from reporting nonesense. This should not be an action that can be taken without consequence.

**Comment by sea212** [comment]
I see your point and I agree. The reason why it is okay for now is that we still have the dispute mechanism. The question is what stake should we take? If it is too low, it doesn't make sense. If it is too high, it becomes exclusive. Another question is what should happen with the oracle stake (I guess slash is the way to go).

I will reduce the priority to medium since this is not pressing (this is a rare case and nothing really concerning happens) and since we have many other more pressing issues at high priority.

**Comment by maltekliemann** [comment]
Two possible suggestions:

- Let the reporter stake `OracleBond`. If their report is correct, reward them (part of) the original oracle bond (which was slashed because the oracle did not report). If their report is incorrect, slash their oracle bond. This incentivizes making a report, but keeps people honest at the same time.
- Don't allow non-oracle reports and go straight to dispute if the oracle fails to report

I really like the second approach.

**Comment by Chralt98** [comment]
Use the issue https://github.com/zeitgeistpm/zeitgeist/issues/868 for this. So I will remove this from the milestone.

**Comment by Chralt98** [comment]
> Don't allow non-oracle reports and go straight to dispute if the oracle fails to report

We decided to allow a non-oracle report, because it's always good to have something we can fallback to. For this, we decided to reserve an `OutsiderBond`, when the oracle did not manage to report in time.
