### ISSUE TITLE
Allow market creators and the Advisory Committee to add on-chain comments to markets

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist#893]
Consider the following scenario: Someone forgets to specify a timezone on an otherwise valid permissionless market. They can later add a comment saying: "All times specified in the market description are in Pacific Time." Similarly, the advisory committee can comment on/flag a market if they feel like something is unclear.

This is different from editing the market since it 1) works on permissionless markets 2) retains the original markets description.

**Comment by Chralt98** [comment]
I think this is tricky. Whenever the description of a market changes, the market participants already traded on the previous information. Means this feature could also be used to confuse the trading activity and in the worst case smash some early traders hard in their faces.

This reminds me of the submarine case on Polymarket, where the description of the market was clearly stating a fact that should be regarded, but the reported outcome was not reflecting this.

Additionally, if we want to integrate this change, I don't think this requires an implementation of us. What you just need is that the market creator signs a message that states the market should be interpreted in Pacific Time. Means in specific terms: Allow the market creator to use the `remark` extrinsic, which allows the market creator to put in the signature of a message that is shown on the front end. This message should include the market id. But again, I don't think this is a good feature, since it confuses traders. I would rather remove the market and create a new one with a correct description.

**Comment by maltekliemann** [comment]
> Whenever the description of a market changes, the market participants already traded on the previous information.

If there's no time zone, then based on what information are they trading? If there's a contradiction in the market description (one date uses Pacific Time, the other uses UTC), is it really a bad idea to clarify this?

Closing because this is too large a project and requires clarification.
