### ISSUE TITLE
Why don't we set `SystemWeightInfo`?

### ISSUE THREAD

**Issue by Chralt98** [zeitgeistpm/zeitgeist#945]
https://github.com/zeitgeistpm/zeitgeist/blob/7e6754fa0a3091ad21c095257664a408b75d6318/runtime/common/src/lib.rs#L1835

**Comment by Chralt98** [comment]
Isn't this the weight result of the `frame_system` benchmark?

**Comment by sea212** [comment]
The line you highlighted is within tests for the fee adjustment. We properly use our custom system weights in the production environment: 

https://github.com/zeitgeistpm/zeitgeist/blob/7e6754fa0a3091ad21c095257664a408b75d6318/runtime/common/src/lib.rs#L408-L436

AFAIK the actual weight is irrelevant for the tests that use the value you highlighted, so it is perfectly fine to use the default weights from the Substrate reference machine. If you can prove that this is not the case, we'd have to set it properly, otherwise we can close this issue.
