### ISSUE TITLE
Review minLiquidity constant usage

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/zeitgeist#998]
When multiple base assets are allowed for a market the `minLiquidity` constant doesn't make much sense as each asset will have a different value. I think either this restriction should be removed or each asset should be configured with it's own `minLiquidity`

**Comment by maltekliemann** [comment]
Good point. The `MinLiquidity` parameter only really serves the purpose of ensuring that balances don't start off below the acceptable numerical values. There's no point enforcing any minimum economic value for the pool, not just because we have base assets of different value, but also because people can withdraw immediately after deploying the pool.

I think we can replace the minimum liquidity checks with a check for minimum allowed balance:

```rust
pub(crate) fn min_balance(asset: Asset<MarketIdOf<T>>) -> BalanceOf<T> {
      T::AssetManager::minimum_balance(asset).max(MIN_BALANCE.saturated_into())
}
```

This boils down to 1 cent (10^8 Pennocks) minimum balance for each asset right now. Sound good?

**Comment by Robiquet** [comment]
Yeah makes sense
